# Generated by Django 3.2.12 on 2023-06-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(choices=[('nature', 'nature'), ('people', 'people'), ('cars', 'cars'), ('buildings', 'buildings')], max_length=40),
        ),
    ]
