# Generated by Django 3.2.12 on 2023-06-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='filter_class',
        ),
    ]
